In [4]:
!pip install matplotlib
!pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Defaulting to user installation because normal site-packages is not writeable
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\nijaa\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

In [6]:
import pandas as pd
import numpy as np
import re, json
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
df = pd.read_csv('The Ultimate Cars Dataset 2024.csv',encoding='cp1252')

In [29]:
df.head(5)

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm

In [30]:
df.isna().sum()

Company Names                0
Cars Names                   0
Engines                      0
CC/Battery Capacity          3
HorsePower                   0
Total Speed                  0
Performance(0 - 100 )KM/H    6
Cars Prices                  0
Fuel Types                   0
Seats                        0
Torque                       1
dtype: int64

In [31]:
def rename_and_clean_speed_column(df):
    """
    Renames the column "Total Speed" to "Total Speed (km/h)"
    and removes " km/h" from its values.

    Parameters:
    df (pd.DataFrame): The input dataframe.

    Returns:
    pd.DataFrame: The updated dataframe with changes.
    """
    if "Total Speed" in df.columns:
        # Rename the column
        df.rename(columns={"Total Speed": "Total Speed (km/h)"}, inplace=True)
        # Remove " km/h" from the values in the column
        df["Total Speed (km/h)"] = df["Total Speed (km/h)"].str.replace(" km/h", "", regex=False)
    else:
        print("Column 'Total Speed' does not exist in the dataframe.")
    
    return df

df = rename_and_clean_speed_column(df)

In [32]:
def rename_and_clean_performance_column(df):
    """
    Renames the column "Performance(0 - 100 )KM/H" to "Performance(0 - 100 )KM/H (in sec)"
    and removes " sec" from its values.

    Parameters:
    df (pd.DataFrame): The input dataframe.

    Returns:
    pd.DataFrame: The updated dataframe with changes.
    """
    if "Performance(0 - 100 )KM/H" in df.columns:
        # Rename the column
        df.rename(columns={"Performance(0 - 100 )KM/H": "Performance(0 - 100 )KM/H (in sec)"}, inplace=True)
        # Remove " sec" from the values in the column
        df["Performance(0 - 100 )KM/H (in sec)"] = df["Performance(0 - 100 )KM/H (in sec)"].str.replace(" sec", "", regex=False)
    else:
        print("Column 'Performance(0 - 100 )KM/H' does not exist in the dataframe.")
    
    return df

df = rename_and_clean_performance_column(df)

In [33]:
def rename_and_clean_battery_capacity_column(df):
    """
    Renames the column "CC/Battery Capacity" to "Battery Capacity (cc)"
    and removes " cc" from its values.

    Parameters:
    df (pd.DataFrame): The input dataframe.

    Returns:
    pd.DataFrame: The updated dataframe with changes.
    """
    if "CC/Battery Capacity" in df.columns:
        # Rename the column
        df.rename(columns={"CC/Battery Capacity": "Battery Capacity (cc)"}, inplace=True)
        # Remove " cc" from the values in the column
        df["Battery Capacity (cc)"] = df["Battery Capacity (cc)"].str.replace(" cc", "", regex=False).replace(",", "", regex=False)
    else:
        print("Column 'CC/Battery Capacity' does not exist in the dataframe.")
    
    return df

df = rename_and_clean_battery_capacity_column(df)

In [36]:
def rename_and_clean_horsepower_column(df):
    """
    Removes " hp" from its values.

    Parameters:
    df (pd.DataFrame): The input dataframe.

    Returns:
    pd.DataFrame: The updated dataframe with changes.
    """
    if "HorsePower" in df.columns:
        # Remove " hp" from the values in the column
        df["HorsePower"] = df["HorsePower"].str.replace(" hp", "", regex=False)
    else:
        print("Column 'HorsePower' does not exist in the dataframe.")
    
    return df

df = rename_and_clean_horsepower_column(df)

In [37]:
def rename_and_clean_torque_column(df):
    """
    Removes " Nm" from its values.

    Parameters:
    df (pd.DataFrame): The input dataframe.

    Returns:
    pd.DataFrame: The updated dataframe with changes.
    """
    if "Torque" in df.columns:
        # Remove " hp" from the values in the column
        df["Torque"] = df["Torque"].str.replace(" Nm", "", regex=False)
    else:
        print("Column 'Torque' does not exist in the dataframe.")
    
    return df

df = rename_and_clean_torque_column(df)

In [38]:
df.head(5)

,Company Names,Cars Names,Engines,Battery Capacity (cc),HorsePower,Total Speed (km/h),Performance(0 - 100 )KM/H (in sec),Cars Prices,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990,963,340,2.5,"$1,100,000",plug in hyrbrid,2,800
1,ROLLS ROYCE,PHANTOM,V12,6749,563,250,5.3,"$460,000",Petrol,5,900
2,Ford,KA+,1.2L Petrol,"1,200",70-85,165,10.5,"$12,000-$15,000",Petrol,5,100 - 140
3,MERCEDES,GT 63 S,V8,"3,982",630,250,3.2,"$161,000",Petrol,4,900
4,AUDI,AUDI R8 Gt,V10,"5,204",602,320,3.6,"$253,290",Petrol,2,560